class BasicPerson{
    String first
    String second
    //def x // def means object // dont use
    //y // doesn't work // dont use

}

x = new BasicPerson(first:'D', second:'N') // map like, autogenerated
sd = new BasicPerson()
x.first
x.second
x.getFirst()
x.first = 'E'
x.setFirst('E')
